name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk unzip zip libstdc++6 libffi-dev libssl-dev libtool pkg-config
          pip3 install --upgrade pip
          pip3 install buildozer Cython

      - name: Accept Android SDK Licenses
        run: |
          mkdir -p ~/.android
          echo '8933bad161af4178b1185d1a37fbf41ea5269c55' > ~/.android/repositories.cfg

      - name: Clean Buildozer (optional)
        run: buildozer android clean || true

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: worktimebuddy-apk
          path: bin/*.apk
